services:
  my-next-chatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - microfrontends
    volumes:
      - .:/app                # ← ホストとコンテナを同期
      - /app/node_modules     # ← node_modules はコンテナ側のみ使用
    working_dir: /app         # ← 作業ディレクトリを設定
    # 開発モードで起動-ホットリロード可能
    command: ["npm", "run", "dev"]
 
networks:
  microfrontends:
    external: true
